<a href="https://colab.research.google.com/github/2303A52137/AIML_2303A52137/blob/main/part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LIST_1

In [8]:
import numpy as np
list1=[1,2,3,4]
array_1=np.array(list1)
array_1


array([1, 2, 3, 4])

LIST_2

In [3]:
import numpy as np
list2=[3,5,7,8]
array2=np.array(list2)
array2

array([3, 5, 7, 8])

TYPE_ARRAY

TYPE_LIST

In [11]:
type(list1)

list

In [10]:
type(array_1)

numpy.ndarray

MATHEMATICAL_OPERATIONS


In [17]:
print("multiplication of two arrays:{array_1}and{array2}",array_1*array2)
print("division of two arrays:{array_1}and{array2}",array_1/array2)
print("poweroff two arrays:{array_1}and{array2}",array_1**array2)



multiplication of two arrays:{array_1}and{array2} [ 3 10 21 32]
division of two arrays:{array_1}and{array2} [0.33333333 0.4        0.42857143 0.5       ]
multiplication of two arrays:{array_1}and{array2} [    1    32  2187 65536]


ADDITION OF TWO ARRAYS

In [27]:
result=np.add(array_1,array2)
result

array([ 4,  7, 10, 12])

np.sin()

In [20]:
import numpy as np
np.sin(2)

0.4121184852417566

np.log()


In [21]:
np.log(3)

1.0986122886681098

np.log(2)

In [24]:
np.log2(1)

0.0

np.exp()

In [25]:
np.exp(2)

7.38905609893065